sonar.projectKey=QuickHaulTransits_location-service
sonar.organization=quickhaultransits

# Source code location
sonar.sources=app.py,services,shared,data

# Tests location
sonar.tests=tests

# Language
sonar.language=py

# Coverage Report
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=tests/**,requirements.txt,Dockerfile
