name: CI — Location Service

on:
  push:
    branches:
      - develop
      - main
      - feature/ci-location
  pull_request:
    branches:
      - develop
      - main
      - feature/ci-location
      
permissions:
  contents: write

jobs:
  sast:
    if: github.event_name == 'pull_request'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_sast.yml@feature/templates
    with:
      service-path: .
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_HOST_URL }}

  # ─── SCA (Snyk) ───
  sca:
    needs: [sast]
    if: github.event_name == 'pull_request'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_sca.yml@feature/templates
    with:
      service-name: location-service
      service-path: .
      runtime: python
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # ─── Notify: Snyk Criticals ───
  notify-snyk:
    needs: [sca]
    if: needs.sca.outputs.critical-found == 'true'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_notify.yml@feature/templates
    with:
      service-name: location-service
    secrets:
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}

  # ─── Temp Docker Build + Trivy Scan ───
  build:
    needs: [sast, sca]
    if: github.event_name == 'pull_request'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_docker-build.yml@feature/templates
    with:
      service-name: location-service
      service-path: .

  # ─── Notify: Trivy Criticals ───
  notify-trivy:
    needs: [build]
    if: needs.build.outputs.trivy-critical == 'true'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_notify.yml@feature/templates
    with:
      service-name: location-service
    secrets:
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}

  # ─── Publish Docker Image (Tag + Build + Push) ───
  publish:
    if: github.event_name == 'push'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_docker-publish.yml@feature/templates
    with:
      service-name: location-service
      environment: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

  # # ──── Update Helm Chart (CD) ────
  # cd:
  #   needs: [publish]
  #   if: needs.publish.result == 'success'
  #   uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_cd-template.yml@main
  #   with:
  #     service-name: location-service
  #     image-tag: ${{ needs.publish.outputs.image-tag }}
  #     environment: ${{ github.ref_name }}
  #   secrets:
  #     HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}

